### ISSUE TITLE
Error listing pods: Kubecaml.Kubernetes.Definitions.Apimachinery.Pkg.Util.Intstr.Int_or_string.t

### ISSUE THREAD

**Issue by actionshrimp** [andrenth/kubecaml#3]
Hi there,

Thanks very much for the lib, it's saving me a whole lot of manual generating so far!

I'm currently seeing an issue when trying to list pods:
`Kubecaml.Kubernetes.Definitions.Apimachinery.Pkg.Util.Intstr.Int_or_string.t` returned during the JSON response parsing.

I think it corresponds to the `port` field in the response - if the `port` field is specified as string (referring to a labelled port), the decoding works ok, e.g.:
```
"readinessProbe": {
  "failureThreshold": 3,
  "httpGet": {
    "path": "/healthz",
    **"port": "http",**
    "scheme": "HTTP"
  }
}
```

But if the port is referred to as a number, the decoding fails, e.g.:
```
"readinessProbe": {
  "failureThreshold": 3,
  "httpGet": {
    "path": "/healthz",
    **"port": 10254,**
    "scheme": "HTTP"
  }
}
```

This seems to be encapsulated by the `io.k8s.apimachinery.pkg.util.intstr.IntOrString` swagger type, which marks the `type` as `string` - so I guess Yojson doesn't like it when it sees a number in the response.

I'll have a look at ocaml-swagger and see if I can figure out a way of making this work - there's an ```[@encoding `string]```  option in ppx_deriving_yojson that might help, but I'm not sure how I'd target the ref in question and apply it, so any suggestions would be gratefully received 😄

**Comment by rizo** [comment]
I'm also seeing this error. 

The generated code for `Int_or_string` is:

```ocaml
module Int_or_string = struct
  type t = string [@@deriving yojson]

  let make t = t

  module Object = Object.Make (struct type value = t [@@deriving yojson] end)
end
```

The `to_yojson` function generated by `ppx_deriving_yojson` will simply translate the values as `` `String ``, which is what it is instructed to do. I think what needs to be done in this case is generate a custom `to_yojson` function that will attempt to decode the string argument as an integer and produce an `` `Int ``. ~~Or of course use @actionshrimp's suggestion – the `` [@encoding `string] `` annotation~~ (Actually this approach doesn't work because it requires a numerical type and always produces a JSON string).

It's not clear how this custom logic can be applied generically for the swagger spec.

**Comment by rizo** [comment]
I submitted a PR to fix this issue https://github.com/andrenth/ocaml-swagger/pull/7

The fix allows the `string` types with the `int-or-string` format to be represented as JSON integers, if they're valid integers, and as JSON strings otherwise.

Simplified example:

```ocaml
# #require "kubecaml";;
# module Int_or_string = Kubecaml.Kubernetes.Definitions.Apimachinery.Pkg.Util.Intstr.Int_or_string;;
# Int_or_string.(create "1883" |> to_yojson);;
- : Yojson.Safe.json = `Int 1883
# Int_or_string.(create "hello" |> M.to_yojson);;
- : Yojson.Safe.json = `String "hello"

# let Ok x = Int_or_string.of_yojson (`Int 43);;
val x : Int_or_string.t = <abstr>
# Int_or_string.to_yojson x;;
- : Yojson.Safe.json = `Int 43
```
